### GET all users
GET http://localhost:3000/users

### GET user by id
GET http://localhost:3000/users/2

### POST user (VALID)

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Abhi",
  "mobile": 65468464,
  "studentEmail": "abcdeg@gmail.com",
  "hobbies": ["gaming","habshd"]
}